apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: auth-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: auth-api
    spec:
      containers:
      - env:
        - name: AUTH_API_PORT
          value: "8081"
        - name: JWT_SECRET
          value: myfancysecret
        - name: USERS_API_ADDRESS
          value: http://users-api:8083
        image: auth-api
        name: auth-api
        ports:
        - containerPort: 8081
        imagePullPolicy: Never
      restartPolicy: Always
