apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: todos-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: todos-api
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: TODO_API_PORT
          value: "8082"
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans
          
        image: todos-api
        name: todos-api
        ports:
        - containerPort: 8082
        imagePullPolicy: Never
      restartPolicy: Always
